name: Azure Pipelines
variables:
  python.version: '3.7.6'
stages:
- stage: Build
  jobs:
  - job: Build
    pool:
      name: Hosted Ubuntu 1604
    steps:
    # Needed for Terraform VM deployment
    - task: InstallSSHKey@0
      inputs:
        knownHostsEntry: 'myVM'
        sshPublicKey: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDSYlwQ6VwV2px7f668OB2KmpVFFtugRNVilnk8Bku4jVeGVuwBp0diDrvPlDLlmKkR+OCh0CtxEI9245rRq+0Fug7HrL7uVP+R/Vx+Wkam90d8Bx+F03Hw25lfoTaANTSR4xV/ri+RWwuhQCLmjeCYeh2g3wSHpIpa5wAJVeWMdIwWfwOquvucRyPQAhufkbzbqzDYTU6p0rTYt/aoTe7dzrcdTLb/zxmxkOiDN+ihKdu0fBt8AiocawgcCC0k2PgPWjpOVrY9tLA0N1ZjYTxzJYSV8MTaDxekYtZQQEsZtfmHuFPqoJEN8YXTJvFPMEKAfSXbrGpPN2MMOS0FTByka6O/aiu+Uieaj3ychHhuXUlMy3z0xwAWj0NZ4IZsWaYC+z75505aHk6r1hry1VjTMliy7GotH2SyXf5UBe0gIq2qa2bAQZy1XAV0o5Del8jc6y8TDbjvNuai6wbYH6vi2PR16VXLxNu8OmyTZxE6RxejFB0u1JFRhuIdUCb4p1NIPO75+3l19pq2yAKDVg4iFp3v5MtuLhkj4wBGu7AfE5owrGCwNgwPz5bxypUeZEQ9vezUgch0vd68qGWKE9u/no3LN1GQWWIEKsgNPNPNOOkF2fierYzqzspZeqkpuTRo+YXzfUsvp+6MnXF5oWse76VcT68hr+zjSriBLYNPPQ== saro@saro-MacBook-Pro.local'
        sshKeySecureFile: 'azure-cicd.pem'
    - task: ArchiveFiles@2
      displayName: 'Archive FakeRestAPI'
      inputs:
        rootFolderOrFile: 'path/to/fakerestapi'
        includeRootFolder: false
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId)-fakerestapi.zip'
    - publish: $(Build.ArtifactStagingDirectory)/$(Build.BuildId)-fakerestapi.zip
      displayName: 'Upload Package'
      artifact: drop-fakerestapi
- stage:
  jobs:
  - deployment: FakeRestAPI
    pool:
      vmImage: 'Ubuntu-16.04'
    environment: 'TEST'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureWebApp@1
            displayName: 'Deploy Azure Web App'
            inputs:
              azureSubscription: '137aa6cc-27a5-4e00-a6ac-b0d20e094fb1'
              appName: 'myWebApp'
              appType: webApp
              package: $(Pipeline.Workspace)/drop-fakerestapi/$(Build.BuildId)-fakerestapi.zip
  - deployment: VMDeploy
    displayName: NAME
    environment:
      name:  ENVIRONMENT NAME
      resourceType: VirtualMachine
      tags: TAG NAME
    strategy:
      runOnce:
        deploy:
          steps:
          - task: Bash@3
            inputs:
              targetType: 'inline'
              script: |
                #! /bin/bash
                
                sudo apt-get upgrade -y
                sudo apt-get install python3-pip -y
                sudo apt-get install unzip -y
                sudo apt-get install -y chromium-browser
                pip3 install selenium
                export PATH=$PATH:some/path


